### ISSUE TITLE
Burrow Server :Error on UI

### ISSUE THREAD

**Issue by balarampuli** [GeneralMills/BurrowUI#12]
Hi Team,

i am getting the "Burrow Server: Error" on the UI screen(see the attachment), and also getting the "Burrow Home Not Set"  at the linux terminal

# node server.js
BURROW_HOME: undefined
Burrow Home Not Set
API running on 0.0.0.0:3000

here, server_config.json contains the following info,
{
  "burrow" : {
    "home" : "http://{hostname}/v2/kafka"
  }
}

I have updated the hostname with right information, but no effect, please suggest me on this to resolve the issue.

Regards,
Balaram
<img width="1679" alt="screen shot 2018-05-06 at 6 32 48 pm" src="https://user-images.githubusercontent.com/21177862/39678561-e2dc9e0a-515c-11e8-90ed-a5e912c9940e.png">

**Comment by petersonnek** [comment]
We recently release an update to Burrow UI. It's a pretty substantial UI change and some backend changes. Can you check if the latest version works for you?

**Comment by ngprice** [comment]
I am seeing this as well. I tried both the docker image (generalmills/burrowui) and building from source, both are giving "Burrow Server: Error" in the top right of the UI. In console I see the following:
```
Backend returned code 200, body was: [object Object]        burrow.service.ts:160
ERROR There was a server error, please try again later.     core.js:1671
```
Here is the error body from setting a breakpoint on handleError() in burrow.service.ts:
```
error: SyntaxError: Unexpected token E in JSON at position 0 
at JSON.parse (<anonymous>)
at XMLHttpRequest.onLoad (http://localhost:3000/vendor.js:7422:51)
at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:7212:31)
at Object.onInvokeTask (http://localhost:3000/vendor.js:36864:33)
at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:7211:36)
at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:3000/polyfills.js:6979:47)
at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:3000/polyfills.js:7287:34)
at invokeTask (http://localhost:3000/polyfills.js:8331:14)
at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/polyfills.js:8357:17)
text: "ERROR: Something Strange Happened"
```
I just get the error text back when I GET from /api/burrow/home:
```
$ curl http://localhost:3000/api/burrow/home
ERROR: Something Strange Happened
```
My local burrow is up:
```
$ curl localhost:8000/v3/kafka
{"error":false,"message":"cluster list returned","clusters":["local"],"request":{"url":"/v3/kafka","host":"9b7c06991901"}}
```

Can provide further details as needed.
