### ISSUE TITLE
ng build throws error

### ISSUE THREAD

**Issue by sr6033** [GeneralMills/BurrowUI#18]
```
/usr/local/lib/node_modules/ng-cli/node_modules/resolve/lib/sync.js:60
    throw err;
    ^

Error: Cannot find module 'ng-factory' from '/home/param/BurrowUI'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/ng-cli/node_modules/resolve/lib/sync.js:58:15)
    at module.exports (/usr/local/lib/node_modules/ng-cli/node_modules/resolve-require/lib/index.js:10:24)
    at Command.<anonymous> (/usr/local/lib/node_modules/ng-cli/lib/index.js:35:5)
    at Command.listener (/usr/local/lib/node_modules/ng-cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/ng-cli/node_modules/commander/index.js:654:12)
    at Command.parse (/usr/local/lib/node_modules/ng-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/ng-cli/lib/index.js:55:9)
    at Module._compile (module.js:635:30)
```

**Comment by cgosiak** [comment]
Which version of Angular are you trying to build it with?

ng --version

**Comment by sr6033** [comment]
The issue has been resolved. I am closing it.
